import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const eau = 4;
const gaz = 1.5;
const elec = 0.5;

export default function Home() {
  const [elecStart, setElectStart] = useState(0);
  const [elecEnd, setElectEnd] = useState(0);
  const [gazStart, setGazStart] = useState(0);
  const [gazEnd, setGazEnd] = useState(0);
  const [eauStart, setEauStart] = useState(0);
  const [eauEnd, setEauEnd] = useState(0);
  const [totalEau, setTotalEau] = useState(0);
  const [totlaGaz, setTotalGaz] = useState(0);
  const [totalElec, setTotalElec] = useState(0);
  const [total, setTotal] = useState(0);

  const handleCalculate = () => {
    setTotalEau(0);
    setTotalElec(0);
    setTotalGaz(0);
    setTotal(0);
    const eauArrDep = eauEnd - eauStart;
    const elecArrDep = elecEnd - elecStart;
    const gazArrDep = gazEnd - gazStart;
    setTotalEau(eauArrDep * eau);
    setTotalElec(elecArrDep * elec);
    setTotalGaz(gazArrDep * gaz);
    const totalPrix = totlaGaz + totalEau + totalElec;
    setTotal(totalPrix);
  };

  return (
    <>
      <Head>
        <title>Santa Lina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.container}`}>
          <div>
            <h2>Arrivée</h2>
            <label htmlFor="elecdep">Electricité</label>
            <input
              type="number"
              id="elecdep"
              min={0}
              onChange={(e) => setElectStart(e.target.value)}
            />
            <label htmlFor="eaudep">Eau</label>
            <input
              type="number"
              id="eaudep"
              min={0}
              onChange={(e) => setEauStart(e.target.value)}
            />
            <label htmlFor="gazdep">Gaz</label>
            <input
              type="number"
              min={0}
              onChange={(e) => setGazStart(e.target.value)}
            />
          </div>
          <div>
            <h2>Départ</h2>
            <label htmlFor="elecend">Electricité</label>
            <input
              type="number"
              id="elecend"
              min={0}
              onChange={(e) => setElectEnd(e.target.value)}
            />
            <label htmlFor="eauend">Eau</label>
            <input
              type="number"
              id="eauend"
              min={0}
              onChange={(e) => setEauEnd(e.target.value)}
            />
            <label htmlFor="gazend">Gaz</label>
            <input
              type="number"
              min={0}
              onChange={(e) => setGazEnd(e.target.value)}
            />
          </div>
          <button onClick={(e) => handleCalculate()}>Calculer</button>
          <div>
            <h2>Totaux:</h2>
            <p>Eau: {totalEau}€</p>
            <p>Gaz: {totlaGaz}€</p>
            <p>Elec: {totalElec}€</p>
            <p>Total: {total}€ </p>
          </div>
        </div>
      </main>
    </>
  );
}
